name:Deploy my project to github pages after push

on:
  push:
    branches:
      - master
      - main


jobs:
  build:
    runs-on:ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Deploy to Vercel
        run: npx vercel --prod
      env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}